# Generated by Django 2.0.2 on 2018-06-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180620_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='discription',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='date',
        ),
        migrations.AddField(
            model_name='bill',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
